// This file is computer-generated by onnx2c 
// (TODO: add creating command line here)
// (TODO: print creation date here )

// ONNX model:
// produced by pytorch, version 2.6.0
// ONNX IR version: 1
// Model documentation: 
/*

*/

#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#define MAX(X,Y) ( X > Y ? X : Y)
#define MIN(X,Y) ( X < Y ? X : Y)
#define CLIP(X,L) ( MAX(MIN(X,L), -L) )

#if __STDC_VERSION__ < 199901L
#define FUNC_PREFIX
#else
#define FUNC_PREFIX static inline
#endif

static const float tensor_models_0_linear_weight[1][3] = 
{
  {-1.7500000000000000000f, 1.1399999856948852539f, 0.56000000238418579102f}
};
static const float tensor_models_0_linear_bias[1] = 
{-6.0700001716613769531f};
static const float tensor_models_1_linear_weight[1][3] = 
{
  {-2.9900000095367431641f, 1.2100000381469726562f, 0.68999999761581420898f}
};
static const float tensor_models_1_linear_bias[1] = 
{-7.4400000572204589844f};
static const float tensor_models_2_linear_weight[1][3] = 
{
  {-1.7400000095367431641f, 0.63999998569488525391f, 0.40000000596046447754f}
};
static const float tensor_models_2_linear_bias[1] = 
{-5.0199999809265136719f};
static const float tensor_models_3_linear_weight[1][3] = 
{
  {-1.7500000000000000000f, 1.1399999856948852539f, 0.56000000238418579102f}
};
static const float tensor_models_3_linear_bias[1] = 
{-6.0700001716613769531f};
static const float tensor_models_4_linear_weight[1][3] = 
{
  {-2.9900000095367431641f, 1.2100000381469726562f, 0.68999999761581420898f}
};
static const float tensor_models_4_linear_bias[1] = 
{-7.4400000572204589844f};
static const float tensor_models_5_linear_weight[1][3] = 
{
  {-1.7400000095367431641f, 0.63999998569488525391f, 0.40000000596046447754f}
};
static const float tensor_models_5_linear_bias[1] = 
{-5.0199999809265136719f};
static const float tensor_val_0[1] = 
{0.28000000119209289551f};
static const float tensor_val_1[1] = 
{0.23000000417232513428f};
static const float tensor_val_2[1] = 
{0.34999999403953552246f};
union tensor_union_0 {
float tensor_linear[1][1];
bool tensor_gt[1][1];
};
static union tensor_union_0 tu0;

union tensor_union_1 {
float tensor_sigmoid[1][1];
float tensor_linear_1[1][1];
bool tensor_gt_1[1][1];
};
static union tensor_union_1 tu1;

union tensor_union_2 {
float tensor_sigmoid_1[1][1];
float tensor_linear_2[1][1];
bool tensor_gt_2[1][1];
};
static union tensor_union_2 tu2;

union tensor_union_3 {
float tensor_sigmoid_2[1][1];
float tensor_linear_3[1][1];
bool tensor_gt_3[1][1];
};
static union tensor_union_3 tu3;

union tensor_union_4 {
float tensor_sigmoid_3[1][1];
float tensor_linear_4[1][1];
bool tensor_gt_4[1][1];
};
static union tensor_union_4 tu4;

union tensor_union_5 {
float tensor_sigmoid_4[1][1];
float tensor_linear_5[1][1];
bool tensor_gt_5[1][1];
};
static union tensor_union_5 tu5;

union tensor_union_6 {
float tensor_sigmoid_5[1][1];
};
static union tensor_union_6 tu6;


/*
 * Operand:           Gemm
 * Name in ONNX file: node_Gemm_0
 */
FUNC_PREFIX void node_node_Gemm_0( const float A[1][3], const float B[1][3], const float C[1], float Y[1][1] )
{
	/* Gemm */
	/* alpha   = 1.0000000000000000000
	   beta    = 1.0000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 3;
	const int N = 1;
	float alpha = 1.0000000000000000000;
	float beta = 1.0000000000000000000;
	float (*C_)[1]  = (float(*)[1])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][0] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Sigmoid
 * Name in ONNX file: node_Sigmoid_1
 */
FUNC_PREFIX void node_node_Sigmoid_1( const float X[1][1], float Y[1][1] )
{
	/* Sigmoid
	   Implemented with Elementwise template.
	   alpha = 0.0000000000000000000
	   beta = 0.0000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<1; i1++) {
		Y[i0][i1] = 1/(1+exp(-X[i0][i1]));
	}
	}
}

/*
 * Operand:           Constant
 * Name in ONNX file: node_Constant_2
 */
FUNC_PREFIX void node_node_Constant_2( const float output[1] )
{
	/* Constant */
	/* The output is generated as a global tensor */
	(void)output;
}

/*
 * Operand:           Greater
 * Name in ONNX file: node_Greater_3
 */
FUNC_PREFIX void node_node_Greater_3( const float A[1][1], const float B[1], bool C[1][1] )
{
	/* Greater
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	unsigned i0, i1;
	for (i0=0; i0<1; i0++) {
	for (i1=0; i1<1; i1++) {
		C[i0][i1] = A[0][0]>B[0];;
	}
	}
}

/*
 * Operand:           Gemm
 * Name in ONNX file: node_Gemm_4
 */
FUNC_PREFIX void node_node_Gemm_4( const float A[1][3], const float B[1][3], const float C[1], float Y[1][1] )
{
	/* Gemm */
	/* alpha   = 1.0000000000000000000
	   beta    = 1.0000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 3;
	const int N = 1;
	float alpha = 1.0000000000000000000;
	float beta = 1.0000000000000000000;
	float (*C_)[1]  = (float(*)[1])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][0] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Sigmoid
 * Name in ONNX file: node_Sigmoid_5
 */
FUNC_PREFIX void node_node_Sigmoid_5( const float X[1][1], float Y[1][1] )
{
	/* Sigmoid
	   Implemented with Elementwise template.
	   alpha = 0.0000000000000000000
	   beta = 0.0000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<1; i1++) {
		Y[i0][i1] = 1/(1+exp(-X[i0][i1]));
	}
	}
}

/*
 * Operand:           Greater
 * Name in ONNX file: node_Greater_6
 */
FUNC_PREFIX void node_node_Greater_6( const float A[1][1], const float B[1], bool C[1][1] )
{
	/* Greater
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	unsigned i0, i1;
	for (i0=0; i0<1; i0++) {
	for (i1=0; i1<1; i1++) {
		C[i0][i1] = A[0][0]>B[0];;
	}
	}
}

/*
 * Operand:           Gemm
 * Name in ONNX file: node_Gemm_7
 */
FUNC_PREFIX void node_node_Gemm_7( const float A[1][3], const float B[1][3], const float C[1], float Y[1][1] )
{
	/* Gemm */
	/* alpha   = 1.0000000000000000000
	   beta    = 1.0000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 3;
	const int N = 1;
	float alpha = 1.0000000000000000000;
	float beta = 1.0000000000000000000;
	float (*C_)[1]  = (float(*)[1])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][0] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Sigmoid
 * Name in ONNX file: node_Sigmoid_8
 */
FUNC_PREFIX void node_node_Sigmoid_8( const float X[1][1], float Y[1][1] )
{
	/* Sigmoid
	   Implemented with Elementwise template.
	   alpha = 0.0000000000000000000
	   beta = 0.0000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<1; i1++) {
		Y[i0][i1] = 1/(1+exp(-X[i0][i1]));
	}
	}
}

/*
 * Operand:           Constant
 * Name in ONNX file: node_Constant_9
 */
FUNC_PREFIX void node_node_Constant_9( const float output[1] )
{
	/* Constant */
	/* The output is generated as a global tensor */
	(void)output;
}

/*
 * Operand:           Greater
 * Name in ONNX file: node_Greater_10
 */
FUNC_PREFIX void node_node_Greater_10( const float A[1][1], const float B[1], bool C[1][1] )
{
	/* Greater
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	unsigned i0, i1;
	for (i0=0; i0<1; i0++) {
	for (i1=0; i1<1; i1++) {
		C[i0][i1] = A[0][0]>B[0];;
	}
	}
}

/*
 * Operand:           Gemm
 * Name in ONNX file: node_Gemm_11
 */
FUNC_PREFIX void node_node_Gemm_11( const float A[1][3], const float B[1][3], const float C[1], float Y[1][1] )
{
	/* Gemm */
	/* alpha   = 1.0000000000000000000
	   beta    = 1.0000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 3;
	const int N = 1;
	float alpha = 1.0000000000000000000;
	float beta = 1.0000000000000000000;
	float (*C_)[1]  = (float(*)[1])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][0] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Sigmoid
 * Name in ONNX file: node_Sigmoid_12
 */
FUNC_PREFIX void node_node_Sigmoid_12( const float X[1][1], float Y[1][1] )
{
	/* Sigmoid
	   Implemented with Elementwise template.
	   alpha = 0.0000000000000000000
	   beta = 0.0000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<1; i1++) {
		Y[i0][i1] = 1/(1+exp(-X[i0][i1]));
	}
	}
}

/*
 * Operand:           Constant
 * Name in ONNX file: node_Constant_13
 */
FUNC_PREFIX void node_node_Constant_13( const float output[1] )
{
	/* Constant */
	/* The output is generated as a global tensor */
	(void)output;
}

/*
 * Operand:           Greater
 * Name in ONNX file: node_Greater_14
 */
FUNC_PREFIX void node_node_Greater_14( const float A[1][1], const float B[1], bool C[1][1] )
{
	/* Greater
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	unsigned i0, i1;
	for (i0=0; i0<1; i0++) {
	for (i1=0; i1<1; i1++) {
		C[i0][i1] = A[0][0]>B[0];;
	}
	}
}

/*
 * Operand:           Gemm
 * Name in ONNX file: node_Gemm_15
 */
FUNC_PREFIX void node_node_Gemm_15( const float A[1][3], const float B[1][3], const float C[1], float Y[1][1] )
{
	/* Gemm */
	/* alpha   = 1.0000000000000000000
	   beta    = 1.0000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 3;
	const int N = 1;
	float alpha = 1.0000000000000000000;
	float beta = 1.0000000000000000000;
	float (*C_)[1]  = (float(*)[1])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][0] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Sigmoid
 * Name in ONNX file: node_Sigmoid_16
 */
FUNC_PREFIX void node_node_Sigmoid_16( const float X[1][1], float Y[1][1] )
{
	/* Sigmoid
	   Implemented with Elementwise template.
	   alpha = 0.0000000000000000000
	   beta = 0.0000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<1; i1++) {
		Y[i0][i1] = 1/(1+exp(-X[i0][i1]));
	}
	}
}

/*
 * Operand:           Greater
 * Name in ONNX file: node_Greater_17
 */
FUNC_PREFIX void node_node_Greater_17( const float A[1][1], const float B[1], bool C[1][1] )
{
	/* Greater
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	unsigned i0, i1;
	for (i0=0; i0<1; i0++) {
	for (i1=0; i1<1; i1++) {
		C[i0][i1] = A[0][0]>B[0];;
	}
	}
}

/*
 * Operand:           Gemm
 * Name in ONNX file: node_Gemm_18
 */
FUNC_PREFIX void node_node_Gemm_18( const float A[1][3], const float B[1][3], const float C[1], float Y[1][1] )
{
	/* Gemm */
	/* alpha   = 1.0000000000000000000
	   beta    = 1.0000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 3;
	const int N = 1;
	float alpha = 1.0000000000000000000;
	float beta = 1.0000000000000000000;
	float (*C_)[1]  = (float(*)[1])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][0] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Sigmoid
 * Name in ONNX file: node_Sigmoid_19
 */
FUNC_PREFIX void node_node_Sigmoid_19( const float X[1][1], float Y[1][1] )
{
	/* Sigmoid
	   Implemented with Elementwise template.
	   alpha = 0.0000000000000000000
	   beta = 0.0000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<1; i1++) {
		Y[i0][i1] = 1/(1+exp(-X[i0][i1]));
	}
	}
}

/*
 * Operand:           Greater
 * Name in ONNX file: node_Greater_20
 */
FUNC_PREFIX void node_node_Greater_20( const float A[1][1], const float B[1], bool C[1][1] )
{
	/* Greater
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	unsigned i0, i1;
	for (i0=0; i0<1; i0++) {
	for (i1=0; i1<1; i1++) {
		C[i0][i1] = A[0][0]>B[0];;
	}
	}
}

/*
 * Operand:           Concat
 * Name in ONNX file: node_Concat_21
 */
FUNC_PREFIX void node_node_Concat_21( const bool input_0[1][1], const bool input_1[1][1], const bool input_2[1][1], const bool input_3[1][1], const bool input_4[1][1], const bool input_5[1][1], bool output[1][6] )
{
	/* Concat */
	int64_t outputOffset;
	outputOffset = 0;
	for (int64_t i = 0, j = 0; i < 1; i++) {
		*((bool*)output + (outputOffset + i)) = *((bool*)input_0 + i);
		if (++j == 1) {
			outputOffset += (5);
			j = 0;
		}
	}
	outputOffset = 1;
	for (int64_t i = 0, j = 0; i < 1; i++) {
		*((bool*)output + (outputOffset + i)) = *((bool*)input_1 + i);
		if (++j == 1) {
			outputOffset += (5);
			j = 0;
		}
	}
	outputOffset = 2;
	for (int64_t i = 0, j = 0; i < 1; i++) {
		*((bool*)output + (outputOffset + i)) = *((bool*)input_2 + i);
		if (++j == 1) {
			outputOffset += (5);
			j = 0;
		}
	}
	outputOffset = 3;
	for (int64_t i = 0, j = 0; i < 1; i++) {
		*((bool*)output + (outputOffset + i)) = *((bool*)input_3 + i);
		if (++j == 1) {
			outputOffset += (5);
			j = 0;
		}
	}
	outputOffset = 4;
	for (int64_t i = 0, j = 0; i < 1; i++) {
		*((bool*)output + (outputOffset + i)) = *((bool*)input_4 + i);
		if (++j == 1) {
			outputOffset += (5);
			j = 0;
		}
	}
	outputOffset = 5;
	for (int64_t i = 0, j = 0; i < 1; i++) {
		*((bool*)output + (outputOffset + i)) = *((bool*)input_5 + i);
		if (++j == 1) {
			outputOffset += (5);
			j = 0;
		}
	}
}


void entry(const float tensor_input[1][3], bool tensor_output[1][6]){
	#pragma HLS INTERFACE s_axilite port=tensor_input
	#pragma HLS INTERFACE s_axilite port=tensor_output
	#pragma HLS INTERFACE s_axilite port=return
	#pragma HLS INLINE recursive
	node_node_Gemm_0( tensor_input, tensor_models_0_linear_weight, tensor_models_0_linear_bias, tu0.tensor_linear);
	node_node_Sigmoid_1( tu0.tensor_linear, tu1.tensor_sigmoid);
	node_node_Constant_2( tensor_val_0);
	node_node_Greater_3( tu1.tensor_sigmoid, tensor_val_0, tu0.tensor_gt);
	node_node_Gemm_4( tensor_input, tensor_models_1_linear_weight, tensor_models_1_linear_bias, tu1.tensor_linear_1);
	node_node_Sigmoid_5( tu1.tensor_linear_1, tu2.tensor_sigmoid_1);
	node_node_Greater_6( tu2.tensor_sigmoid_1, tensor_val_0, tu1.tensor_gt_1);
	node_node_Gemm_7( tensor_input, tensor_models_2_linear_weight, tensor_models_2_linear_bias, tu2.tensor_linear_2);
	node_node_Sigmoid_8( tu2.tensor_linear_2, tu3.tensor_sigmoid_2);
	node_node_Constant_9( tensor_val_1);
	node_node_Greater_10( tu3.tensor_sigmoid_2, tensor_val_1, tu2.tensor_gt_2);
	node_node_Gemm_11( tensor_input, tensor_models_3_linear_weight, tensor_models_3_linear_bias, tu3.tensor_linear_3);
	node_node_Sigmoid_12( tu3.tensor_linear_3, tu4.tensor_sigmoid_3);
	node_node_Constant_13( tensor_val_2);
	node_node_Greater_14( tu4.tensor_sigmoid_3, tensor_val_2, tu3.tensor_gt_3);
	node_node_Gemm_15( tensor_input, tensor_models_4_linear_weight, tensor_models_4_linear_bias, tu4.tensor_linear_4);
	node_node_Sigmoid_16( tu4.tensor_linear_4, tu5.tensor_sigmoid_4);
	node_node_Greater_17( tu5.tensor_sigmoid_4, tensor_val_0, tu4.tensor_gt_4);
	node_node_Gemm_18( tensor_input, tensor_models_5_linear_weight, tensor_models_5_linear_bias, tu5.tensor_linear_5);
	node_node_Sigmoid_19( tu5.tensor_linear_5, tu6.tensor_sigmoid_5);
	node_node_Greater_20( tu6.tensor_sigmoid_5, tensor_val_1, tu5.tensor_gt_5);
	node_node_Concat_21( tu0.tensor_gt, tu1.tensor_gt_1, tu2.tensor_gt_2, tu3.tensor_gt_3, tu4.tensor_gt_4, tu5.tensor_gt_5, tensor_output);
}
