# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class CNetPlusScalar_simple_noback(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(CNetPlusScalar_simple_noback, self).__init__()
        self.module_0 = py_nndct.nn.Input() #CNetPlusScalar_simple_noback::input_0(CNetPlusScalar_simple_noback::nndct_input_0)
        self.module_1 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[5, 5], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv1]/ret.3(CNetPlusScalar_simple_noback::nndct_conv2d_1)
        self.module_2 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.5(CNetPlusScalar_simple_noback::nndct_relu_2)
        self.module_3 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/937(CNetPlusScalar_simple_noback::nndct_maxpool_3)
        self.module_4 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv2]/ret.7(CNetPlusScalar_simple_noback::nndct_conv2d_4)
        self.module_5 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.9(CNetPlusScalar_simple_noback::nndct_relu_5)
        self.module_6 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/975(CNetPlusScalar_simple_noback::nndct_maxpool_6)
        self.module_7 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv3]/ret.11(CNetPlusScalar_simple_noback::nndct_conv2d_7)
        self.module_8 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.13(CNetPlusScalar_simple_noback::nndct_relu_8)
        self.module_9 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/1013(CNetPlusScalar_simple_noback::nndct_maxpool_9)
        self.module_10 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv4]/ret.15(CNetPlusScalar_simple_noback::nndct_conv2d_10)
        self.module_11 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.17(CNetPlusScalar_simple_noback::nndct_relu_11)
        self.module_12 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/1051(CNetPlusScalar_simple_noback::nndct_maxpool_12)
        self.module_13 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv5]/ret.19(CNetPlusScalar_simple_noback::nndct_conv2d_13)
        self.module_14 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.21(CNetPlusScalar_simple_noback::nndct_relu_14)
        self.module_15 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/1089(CNetPlusScalar_simple_noback::nndct_maxpool_15)
        self.module_16 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv6]/ret.23(CNetPlusScalar_simple_noback::nndct_conv2d_16)
        self.module_17 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.25(CNetPlusScalar_simple_noback::nndct_relu_17)
        self.module_18 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/1127(CNetPlusScalar_simple_noback::nndct_maxpool_18)
        self.module_19 = py_nndct.nn.Conv2d(in_channels=3, out_channels=3, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Conv2d[conv7]/ret.27(CNetPlusScalar_simple_noback::nndct_conv2d_19)
        self.module_20 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.29(CNetPlusScalar_simple_noback::nndct_relu_20)
        self.module_21 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/MaxPool2d[pool]/1165(CNetPlusScalar_simple_noback::nndct_maxpool_21)
        self.module_22 = py_nndct.nn.Module('nndct_flatten') #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.31(CNetPlusScalar_simple_noback::nndct_flatten_22)
        self.module_23 = py_nndct.nn.Linear(in_features=12, out_features=30, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Linear[fc1]/ret.33(CNetPlusScalar_simple_noback::nndct_dense_23)
        self.module_24 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.35(CNetPlusScalar_simple_noback::nndct_relu_24)
        self.module_25 = py_nndct.nn.Linear(in_features=30, out_features=30, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Linear[fc2]/ret.37(CNetPlusScalar_simple_noback::nndct_dense_25)
        self.module_26 = py_nndct.nn.ReLU(inplace=False) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/ret.39(CNetPlusScalar_simple_noback::nndct_relu_26)
        self.module_27 = py_nndct.nn.Linear(in_features=30, out_features=1, bias=True) #CNetPlusScalar_simple_noback::CNetPlusScalar_simple_noback/Linear[fc3]/ret(CNetPlusScalar_simple_noback::nndct_dense_27)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_0 = self.module_5(output_module_0)
        output_module_0 = self.module_6(output_module_0)
        output_module_0 = self.module_7(output_module_0)
        output_module_0 = self.module_8(output_module_0)
        output_module_0 = self.module_9(output_module_0)
        output_module_0 = self.module_10(output_module_0)
        output_module_0 = self.module_11(output_module_0)
        output_module_0 = self.module_12(output_module_0)
        output_module_0 = self.module_13(output_module_0)
        output_module_0 = self.module_14(output_module_0)
        output_module_0 = self.module_15(output_module_0)
        output_module_0 = self.module_16(output_module_0)
        output_module_0 = self.module_17(output_module_0)
        output_module_0 = self.module_18(output_module_0)
        output_module_0 = self.module_19(output_module_0)
        output_module_0 = self.module_20(output_module_0)
        output_module_0 = self.module_21(output_module_0)
        output_module_0 = self.module_22(input=output_module_0, start_dim=1, end_dim=-1)
        output_module_0 = self.module_23(output_module_0)
        output_module_0 = self.module_24(output_module_0)
        output_module_0 = self.module_25(output_module_0)
        output_module_0 = self.module_26(output_module_0)
        output_module_0 = self.module_27(output_module_0)
        return output_module_0
